### ISSUE TITLE
Add support for postgres_backup_databases_custom

### ISSUE THREAD

**Issue by moan0s** [mother-of-all-self-hosting/ansible-role-postgres-backup#5]
Adding support for this would enable to also back up databases that are created as part of [running multiple instances of a service](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/running-multiple-instances.md)

Here is how this would look like (if I have time, I'll add support for this myself but I wanted to note this down)
```yaml
postgres_backup_databases: "{{ postgres_backup_databases_auto + postgres_backup_databases_custom }}"
postgres_backup_databases_auto: []
postgres_backup_databases_custom: []
```
